version: '3.7'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    ports:
      - "1435:1433"
    environment:
      MSSQL_SA_PASSWORD: 'Passw0rd'
      ACCEPT_EULA: 'Y'